### ISSUE TITLE
Passing environment parameter in jenkinsfile not working

### ISSUE THREAD

**Issue by ragebflame** [morficus/Parameterized-Remote-Trigger-Plugin#25]
Hi,

I am having trouble passing an environment parameter to the triggerRemoteJob in my jenkinsfile.

```
pipeline {
    environment {
        TARGET = "Test"
    }
    agent any   // Use any agent 
    stages{
        stage("Trigger remote job"){
            steps {
                triggerRemoteJob job: 'remote_job_test',
                                 maxConn: 1,
                                 parameters: 'TARGET=${TARGET}',
                                 remoteJenkinsName: 'jenkinssrv1',
                                 useCrumbCache: true,
                                 useJobInfoCache: true
            }// steps
        }//stage        
    }  // stages
} // pipeline
```

Produces this error output:

```
ERROR: Remote build failed with 'IOException' for the following reason:
org.jenkinsci.plugins.tokenmacro.MacroEvaluationException:
Unrecognized macro 'TARGET' in 'TARGET=${TARGET}''.

IOException: org.jenkinsci.plugins.tokenmacro.MacroEvaluationException:
Unrecognized macro 'TARGET' in 'TARGET=${TARGET}'
```

If i pass a string value it will kick off the job correctly, but I need to be able to pass a variable in here.

Thanks,
Dan

**Comment by yorammi** [comment]
It should be:
pipeline {
    environment {
        TARGET = "Test"
    }
    agent any   // Use any agent 
    stages{
        stage("Trigger remote job"){
            steps {
                triggerRemoteJob job: 'remote_job_test',
                                 maxConn: 1,
                                 parameters: 'TARGET='+TARGET,
                                 remoteJenkinsName: 'jenkinssrv1',
                                 useCrumbCache: true,
                                 useJobInfoCache: true
            }// steps
        }//stage        
    }  // stages
} // pipeline
